plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lucky.mixflipouter'
    compileSdk 36

    defaultConfig {
        applicationId 'com.lucky.mixflipouter'
        minSdk 30
        targetSdk 36
        versionCode 18
        versionName '0.7.1-p1'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    implementation 'com.google.android.material:material:1.14.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
